server:
  port: 8082
spring:
  application:
    name: store
  data:
    mongodb:
      uri: mongodb://localhost:27017/storeDB
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/